package com.luv2code.productservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@DynamoDBTable(tableName = "products")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Product {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String productId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private Double price;

    @DynamoDBVersionAttribute
    private Long version;
}
